# Usa a imagem oficial do Node.js baseada em Alpine.
FROM node:18-alpine

# Define o diretório de trabalho.
WORKDIR /app

# Instala as dependências.
COPY package*.json ./
RUN npm install

# Copia o restante do código-fonte da aplicação.
COPY . .

# Expõe a porta que o NestJS utiliza por padrão.
EXPOSE 3000

# Comando para iniciar o servidor em modo de desenvolvimento com hot-reloading.
# "npm run start:dev" é o comando padrão em projetos NestJS.
CMD ["npm", "run", "start:dev"]